Messages = {
	
	// COMMON CONTENT SECTION. KEEPT IT TOP OF MODULE SECTIONS.
	"lbl.name"						:	"Bijesh",
	"lbl.age"						:	"Major",
	"lbl.comment"					: 	"Comment",					
	"login.btn.label" 				: 	"Login",
	"login.placeholder.userid"		: 	"UserID",
	"login.placeholder.password" 	: 	"Password",
	"login.failure.message" 		: 	"Invalid UserID / Password...",
	"btn.clear"						: 	"Clear",
	"btn.search"					: 	"Search",
	"btn.show"						: 	"Show",
	"btn.showmodule"				: 	"Show Module",
	"btn.showcar"					: 	"Show Car",
	"btn.addtransaction"			: 	"Add Transaction",
	"btn.addnew"					: 	"Add New",
	"btn.editcar"					: 	"Edit Car",
	"btn.close"						: 	"Close",
	"btn.cancel"					: 	"Cancel",
	"btn.save"						: 	"Save",
	"common.title.vehicleinfo"		: 	"Vehicle Info",
	"copyright"						: 	"&copy; 2018-2019 to aCUBE",

	"help.estimatemanager.selectcustomer"		: 	"To view existing ESTIMATES or create a new ESTIMATE, then please select a CUSTOMER from the dropdown box. If no ESTIMATE, then please Generate one using the Add New button.",
	"help.quotemanager.selectcustomer"			: 	"To view existing QUOTATIONS or create a new QUOTATION, then please select a CUSTOMER from the dropdown box. If no QUOTATION, then please Generate one using the Add New button.",


	

	"menu.customer"					: 	"Customer Manager",
	"menu.estimate"					: 	"Estimate Manager",
	"menu.quote"					: 	"Quotation Manager",
	"menu.cashreceipt"				: 	"Cash Receipt",
	"menu.invoice"					: 	"Invoice",
	"menu.myaccount"				: 	"My Account",
	"menu.logout"					: 	"Logout",
	"menu.users"					:	"Users",
	"menu.marketingbasket"			: 	"Marketing Basket",
	"menu.labour"					:	"Labour Manager",
	"menu.payment"					:	"Payment Manager",
	"menu.vendor"					:	"Vendor Manager",
	"menu.po"						:	"Purchase Order",
	"menu.dashboard"				:	"Dashboard",
	"menu.opexp"					:	"Operational Expense",
	"menu.settings"					:	"Settings",


	"placeholder.selectone"			: 	"Select One",
	"placeholder.selectcustomer"	: 	"Select customer",
	"placeholder.comment"			: 	"Comment",
	"placeholder.address"			: 	"Address",
	"placeholder.selectlocation"	: 	"Select Location",
	"placeholder.selectuser"		:	"Select User",
	"placeholder.selectvendor"		:	"Select Vendor",
	"placeholder.specialnote"		:	"Special notes and Comments",
	
	"pdf.generatepdf.estimate"		:	"Generate PDF for Estimate",
	"pdffootet.thanknote.default"	:	"Please contact Sangeetha for any clarification either email to sangi@iagham.in or call +91 9047474350",

	"validation.status"				: 	"Status is mandatory",
	"validation.userid"				: 	"User ID is mandatory.",
	"validation.password"			: 	"Password is mandatory.",
	"validation.fullname"			: 	"Fullname is mandatory",
	"validation.name"				: 	"Name is mandatory",
	"validation.mobile"				: 	"Mobile is mandatory",
	"validation.password"			: 	"Password is mandatory",
	"validation.role"				: 	"Role is mandatory",
	"validation.avatar"				: 	"Avatar is mandatory",
	"validation.customertype"		: 	"Customer Type is mandatory",
	"validation.address"			: 	"Address is mandatory",
	"validation.email"				: 	"Email is mandatory",
	"validation.selectcustomer"		: 	"Please select a Customer",
	"validation.description"		: 	"Description is mandatory",
	"validation.qty"				: 	"Quantity is mandatory",
	"validation.unit"				: 	"Unit is mandatory",
	"validation.percost"			: 	"Per cost is mandatory",
	"validation.amount"				: 	"Amount is mandatory",
	"validation.location"			: 	"Location is mandatory",
	"validation.email.format"		:	"Email format is wrong",
	"validation.contactperson"		:	"Contact Person is mandatory",
	"validation.payfrom"			:	"Pay from is mandatory",
	"validation.payto"				:	"Pay To is mandatory",
	"validation.date"				:	"Date is mandatory",
	"validation.vendorid"			:	"Vendor is mandatory",
	"validation.paytype"			:	"Payment Type is mandatory",
	"validation.expenseitem"		:	"Expense Item is mandatory",
	"validation.comment"			:	"Comment is mandatory",
	"validation.mode"				:	"Payment Mode is mandatory",
	"validation.purpose"			:	"Purpose is mandatory",
	"validation.refnumber"			:	"Reference Number is mandatory",
	"validation.labour"				:	"Labour is mandatory",
	"validation.week"				:	"Week is mandatory",
	"validation.shift"				:	"Shift is mandatory",
	"validation.pershift"			:	"Shift Amount is mandatory",
	"validation.salary"				:	"Salary is mandatory",
	"validation.noteheader"			:	"Note Header is mandatory",
	"validation.notedescription"	:	"Note Description is mandatory",
	"validation.customer"			:	"Customer is mandatory",

	"validation.customerstatus.confimred"	:	"Can not change the status as CONFIRMED with out QUOTATION approved. Please follow the flow and ensure the QUOTATION is approved",


	"edit.form.confirmation.title"		: 	"Edit confirmation check",
	"edit.form.confirmation.body"		: 	"There are some data updated in the CRUD form. Please check it or press YES to close the Wwindow",



	"breadcrumb.dashboard"				:	"Dashboard",
	"breadcrumb.travel"					:	"Travel",
	

	"modal.update.title" 		: 	"updated",
	"modal.update.message"		:	"Data updated successfully!",
	"modal.add.title" 			: 	"added",
	"modal.add.message"			:	"Data added successfully!",
	"modal.delete.title"		: 	"deleted",
	"modal.delete.message"		:	"Data deleted successfully!",


	"cnt.rows"								:	"Record : ",
	"cnt.total"								:  	"Total Amount : ",
	"table.row.header"						:	"records found",

	"tooltip.edit" 			: 	"Edit",
	"tooltip.add" 			: 	"Add",
	"tooltip.trash" 		: 	"Trash",
	"tooltip.comment"		: 	"Comment",
	"tooltip.refresh"		:	"Refresh",
	"tooltip.additem"		: 	"Add Item",
	"tooltip.view"			:	"View",
	"tooltip.filldesc"		:	"Fill Description",
	"tooltip.addcustomer"	:	"Add Customer",
	"tooltip.trashcustomer"	:	"Trash Customer",
	"tooltip.viewcustomer"	:	"View Customer",
	"tooltip.editcustomer"	:	"Edit Customer",
	"tooltip.dashboard.marketingbasket"			:	"Click to view Marketing Basket",
	"tooltip.dashboard.paymenttransactions"			:	"Click to view Payment Manager",
	"tooltip.refnumber-help"				:	"Cheque#, DD#, Wire Transfer#, NA if its Cash etc.",
	"tooltip.editshift"							:	"Edit Shift",
	"tooltip.editshiftamount"					:	"Edit Shift Amount",
	"tooltip.viewcustomernote"						:	"View Customer Note",

	"setting.language.malayalam"				: 	"Malayalam",
	"setting.language.english"					: 	"English",

	"generalinfo.one" : "Facility is not available at this moment. Visit again later",

	"validation.header"				: 	"Please correct the below listed errors",
	"page.access.denied"			: 	"You do not have sufficient privilege to access this page. Please contact admin to get the permisssion to view the page. For security reason you are logged out, please login again.",

// LOGIN MODULE
	
// ------------------------------------------------------------------------------------------

	"label.expirydate"						:	"Expiry Date",
	"label.paymentdetails"					:	"Payment Details",
	"label.thanknotefooter"					:	"Footer thank note",
	"label.select"							:	"Select",
	"label.sno"								:	"SNO",
	"label.netvalue"						:	"Net Amount",
	"label.discount"						:	"Discount",
	"label.specialnotefooter"				:	"Footer Note",
	"label.id"								:	"ID",
	"label.settings.precontent"				:	"Pre Fill Content",
	"label.precontent"						:	"Pre Content",
	"label.settings.locations"				:	"Manage Locations",
	"label.settings.labours"				:	"Manage Labours",
	"label.locationid"						:	"Location ID",
	"label.specialnote"						:	"Special Note",
	"label.cancel"							:	"Cancel",
	"label.savelabour"						:	"Save Labour",
	"label.fullname"						: 	"Full name",
	"label.name"							:	"Name",
	"label.userid"							: 	"User id",
	"label.password"						: 	"Password",
	"label.mobile"							: 	"Mobile",
	"label.role"							: 	"Role",
	"label.avatar"							: 	"Avatar",
	"label.modifiedby"						: 	"Modified By",
	"label.modifieddate"					: 	"Modified Date",
	"label.status"							: 	"Status",
	"label.createddate"						: 	"Created Date",
	"label.createdby"						: 	"Created By",
	"label.comment"							: 	"Comment",
	"label.customerid"						: 	"Customer ID",
	"label.email"							: 	"Email",
	"label.actions"							: 	"Actions",
	"label.entity"							: 	"Entity",
	"label.address"							: 	"Address",
	"label.customertype"					: 	"Customer Type",
	"label.customerid"						: 	"Customer ID",
	"label.estimatemanager"					: 	"Estimate Manager",
	"label.estimateid"						: 	"Estimate ID",
	"label.description"						: 	"Description",
	"label.quantity"						: 	"QTY",
	"label.units"							: 	"Units",
	"label.price"							: 	"Price",
	"label.rate"							: 	"Rate",
	"label.percost"							: 	"RATE",
	"label.sortorder"						:	"Sort Order",
	"label.amount"							: 	"Amount",
	"label.total"							: 	"Total",
	"label.customer"						: 	"Customer",
	"label.customername"					: 	"Customer Name",
	"label.generatepdf"						: 	"Generate PDF",
	"label.cloneestimate"					: 	"Clone Estimate",
	"label.generatequotation"				: 	"Generate Quotation",
	"label.location"						: 	"Location",
	"label.preparedby"						: 	"Prepared by",
	"label.quoteid"							:	"QuoteID",
	"label.fromdate"						:	"From date",
	"label.todate"							:	"To Date",
	"label.softlock"						:	"Soft Locked: Since the Estimate is cloned, not able to clone / update the current estimate.",
	"label.hardlock"						:	"Hard Locked :  Customer is locked from generating / updating Estimates",
	"label.expenseitem"						:	"Expense Item",							
	"label.user"							: 	"User",
	"label.password"						: 	"Password",
	"label.nodatafound"						: 	"No Record Found.",
	"label.subtotal"						: 	"Sub Total",
	"label.backtoestimate"					: 	"Back to Estimate",
	"label.backtoquote"						: 	"Back to Quotation",
	"label.clonequote"						:	"Clone Quotation",
	"label.approvequote"					:	"Approve Quotation",
	"label.approved"						:	"Approved Quotation",
	"label.whopaid"							:	"Who Paid",
	"label.whomepaid"						:	"Whome Paid",
	"label.vendorid"						:	"Vendor ID",
	"label.vendor"							:	"Vendor",
	"label.contactperson"					:	"Contact Person",
	"label.towhome"							:	"To Whome",
	"label.date"							:	"Date",
	"label.payfrom"							:	"Pay From",
	"label.payto"							:	"Pay To",
	"label.cashonhand"						:	"Cash on Hand",
	"label.transactions"					:	"Transactions",
	"label.latest10customers"				:	"Latest 10 Customers",
	"label.customerstatus"					:	"Customer Status",
	"label.payment.transactions"			:	"Payment Transaction",
	"label.payment.paidamount"				:	"Payment Total Paid",
	"label.dashboard.noaccess"				:	"You do not have Privillige to access anything. <br>Please contact Administrator.",
	"label.typeofpayment"					:	"Type of Payment",
	"label.amountdebitedfrom"				:	"Amount will be debited from created by user account...",
	"clone.success"							:	"Cloned Version",
	"label.correcterrors"					:	"Please correct the below listed errors",
	"label.poid"							:	"POID",
	"label.estimatestatus"					:	"Estimate Status",
	"label.quoteapproved"					:	"Quote Approved",
	"label.projectcost"						:	"Project Cost",
	"label.paidsofar"						:	"Paid So Far",
	"label.balance"							:	"Balance",
	"label.backtopo"						:	"Back to Purchase Order",
	"label.materialexpenses"				:	"Material Expenses",
	"label.labourexpenses"					:	"Labour Expenses",
	"label.projectcash"						:	"Project Cash",
	"label.operationalcash"					:	"Operational Cash",
	"label.spent"							:	"Spent",
	"label.balance"							:	"Balance",
	"label.opexpid"							:	"OPEXPID",
	"label.backtoopexp"						:	"Back to Operational Expense Manager",
	"label.latest10payments"				:	"Latest 10 Payment Transactions",
	"label.paidpo"							:	"Paid for Purchase order",
	"label.paidopexp"						:	"Paid for Operational Expense",
	"label.purpose"							:	"Purpose",
	"label.refnumber"						:	"Reference Number",
	"label.mode"							:	"Mode of Payment",
	"label.totalexpenses"					:	"Total Expenses",
	"label.difference"						:	"Difference (Profit / Loss)",
	"label.selectmonth"						:	"Select Month",
	"label.weeks"							:	"Weeks",
	"label.labour"							:	"Labour",
	"label.labourmanager.shiftheading"		:	"Shift Entry",
	"label.errorcontent"					:	"Sorry! there is no data found..",
	"label.totalshifts"						:	"Total Shifts",
	"label.pershift"						:	"Amount Per Shift",
	"label.salary"							:	"Salary",
	"label.saveamount"						:	"Save Amount",
	"label.saveshift"						:	"Save Shift",
	"label.viewnote"						:	"List of Notes",
	"label.backto.customerview"				:	"Back to Customer View",
	"label.backto.customermanager"			:	"Back to Customer Manager",
	"label.noteheader"						:	"Note Heading",
	"label.notedescription"					:	"Note Description",
	"label.addlabourshift"					:	"Add Labour Shift",
	"label.editlabourshift"					:	"Edit Labour Shift",
	"label.viewlabourshift"					:	"View Labour Shift",
	"label.mandays"							:	"Mandays",
	"label.labourid"						:	"Labour ID",
	"label.save"							:	"Save",

	"SHIFT001"								:	"Labour is already added for this week for the same customer",

	"prompt.info.title"						:	"Info",
	"prompt.label.referencenotloaded"		:	"Reference not loaded successfully, Please refresh the page once again...",
	"prompt.label.permissionissue"			:	"There is some issue with Permissions. Please contact Administrator",

	// DASHBOARD .....

	"dashboard.pageheader"					: 	"Dashboard",

	// MYACCOUNT.......

	"myaccount.pageheader"					: 	"My Account",
	"myaccount.avatar"						: 	"Avatar",
	"myaccount.basicinfo"					: 	"Basic information",
	"myaccount.edituser"					: 	"Edit user",

	// USERMANAGER.....

	"usermanager.pageheader"				: 	"User manager",
	"usermanager.users"						: 	"Users",
	"usermanager.edituser"					: 	"Edit User",
	"usermanager.adduser"					: 	"Add user",

	// CUSTOMER MANAGER ...

	"customermanager.pageheader"				: 	"Customer Manager",
	"customermanager.customerview.pageheader"	: 	"Customer",
	"customermanager.customerview"				: 	"Customer",
	"customermanager.basicdetails"				:	"Basic Info",
	"customermanager.expensedetails"			:	"Expense Info",
	"customermanager.paymentdetails"			:	"Payment Info",
	"customermanager.customers"					: 	"Customers",
	"customermanager.add"						: 	"Add Customer",
	"customermanager.edit"						: 	"Edit Customer",
	"customermanager.pos"						:	"Purchase Orders",
	"customermanager.quotes"					:	"Quotations",
	"customermanager.estimates"					:	"Estimates",
	"customermanager.customerpay"				:	"Customer Pay",
	"customermanager.notes"						:	"List of Notes",
	"customermanager.noteedit"					:	"Edit Note",
	"customermanager.noteadd"					:	"Add Note",
	"customermanager.labourdetails"				:	"Labour Details",
	"customermanager.customernote"				:	"Customer Notes",
		// MARKETING BASKET....

	"marketingbasket.pageheader"			: 	"Marketing Basket",
	"marketingbasket.customers"				: 	"Customers",
	"marketingbasket.edit"					: 	"Edit Customer details",
	"marketingbasket.add"					: 	"Add Customer details",

	// ESTIMATE MANAGER

	"estimatemanager.pageheader"					: 	"Estimate Manager",
	"estimatemanager.selectcustomer"				: 	"Select a Customer",
	"estimatemanager.add"							: 	"Add Estimate",
	"estimatemanager.edit"							: 	"Edit Estimate",
	"estimatemanager.estimate"						: 	"Estimate",
	"estimatemanager.estimategenerate.pageheader"	: 	"Estimate Generate",
	"estimatemanager.estimatebasket.pageheader"		: 	"Estimate Basket",
	"estimatebasket.description.prefill"			: 	"Suppy and installation of Customized Base Unit with Shutter and Shelves in 18mm thk Branded Ply including all necessory materials for fixing. As per drawing details and specs. Location: Living Room",
	"estimatebasket.generatepdf.estimate"			: 	"Estimate",
	"estimatebasket.pdfnote"						: 	"Note",
	"estimatebasket.pdfnote.one"					: 	"Tax as applicable",
	"estimatebasket.pdfnote.two"					: 	"Actual Measurement in Feet system (3',6',9')",
	"estimatebasket.pdfnote.three"					: 	"Wallpaper pricing on confirmation of sample",
	"estimatebasket.pdfnote.four"					: 	"Plywood Branded Brand or Greenply or Marinolam or Equivalent",
	"estimatebasket.pdfnote.five"					: 	"Laminate Merino or Asis or Suntek or Greenlam laminate",
	"estimatebasket.pdfnote.six"					: 	"Civil and Electrical and plumbing works on actuals",
	"estimatebasket.pdfnote.seven"					: 	"False Ceiling Cove light is included, spot lights (panel lights) pricing will be on actuals",
	"estimatebasket.pdffooter.one"					: 	"Please Revert for any Clarification. Looking forward to serving you.",
	"estimatebasket.pdffooter.two"					: 	"If you have any questions concerning this quotation, contact Sangeetha, +919047474350, sangi@inagham.com.",
	"estimatebasket.deleteitem"						: 	"Do you want to delete the estimate item ? Click YES to delete the item, Click NO to cancel the action.",
	"estimatebasket.editestimatebasketitem"			:	"Edit Estimate Basket Item",
	

	"quotemanager.pageheader"					: 	"Quotation Manager",
	"quotemanager.quotes"						:	"Quotations",
	"quotemanager.quotebasket.pageheader"		: 	"Quote Basket",
	"quotebasket.editquotebasketitem"			:	"Edit Quote Basket item",
	"quotebasket.deleteitem"					:	"Do you want to delete the quotation item ? Click YES to delete the item, Click NO to cancel the action.",
	
	"paymentmanager.pageheader"					:	"Payment Manager",
	"paymentmanager.newpay"						:	"New Payment",
	"paymentmanager.edit"						:	"Edit Payment",

	"vendormanager.pageheader"					:	"Vendor Manager",
	"vendormanager.vendors"						:	"Vendors",
	'vendormanager.add'							:	"Add Vendor",

	"labourmanager.pageheader"					:	"Labour Manager",
	"labourmanager.view"						:	"Labour Shift View",
	"labourmanager.editshift"					:	"Labour Shift Edit",
	"labourmanager.editlabour"					:	"Edit Labour",
	


	// PO MANAGER
	"pomanager.pageheader"						:	"Purchase Order Manager",
	"pomanager.pobasket.pageheader"				:	"Purchase Order Basket",
	"pomanager.pos"								:	"Purchase Orders",
	"pobasket.deleteitem"						: 	"Do you want to delete the PO item ? Click YES to delete the item, Click NO to cancel the action.",
	"pobasket.editpobasketitem"					:	"PO Basket Edit Item",
	"opexpmanager.pageheader"					:	"Operational Expense Manager",
	"opexpmanager.opexps"						:	"Operational Expenses",
	"opexpbasket.editopexpbasketitem"			:	"Edit Operation Expense Basket Item",
	"opexpmanager.opexpbasket.pageheader"		:	"Operational Expenses Basket",
	"opexpbasket.deleteitem"					:	"Do you want to delete the Operational Expense item ? Click YES to delete the item, Click NO to cancel the action.",

	"todo.todoclient.todolist"					:	"Todo List",
	"settings.pageheader"						:	"Settings",
	"settings.editlocation"						:	"Edit Location",
	"settings.editprefill"						:	"Edit Pre content",
	"settings.prefill"							:	"Prefill",
	"settings.sortorder"						:	"Sorting Order"






}
